<div class="container">
    <h3>Listado de géneros</h3>
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Descripción</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($generos as $genero) { ?>
                <tr>
                    <td> <?= $genero->id_genero ?></td>
                    <td>
                        <?php if ($id_editar == $genero->id_genero) { ?>
                            <form action="updateGenero/<?= $genero->id_genero ?>" method="POST">
                                <div class="input-group">
                                    <input required name="descripcion" type="text" class="form-control" value="<?= $genero->descripcion ?>">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-primary">Guardar</button>
                                    </div>
                                </div>
                                <a href="volverAbmGenero" type="button" class="btn btn-secondary">Cancelar</a>
                            </form>
                        <?php } else { ?>
                            <?= $genero->descripcion; ?>
                        <?php } ?>
                    </td>
                    <td>
                        <?php if ($id_editar != $genero->id_genero) { ?>
                            <a href="editarGenero/<?= $genero->id_genero ?>" class="btn btn-success">Editar</a>
                            <a href="eliminarGenero/<?= $genero->id_genero ?>" class="btn btn-danger">Borrar</a>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <div class="mt-4">
        <h3>Agregar nuevo género</h3>
            <?php require_once 'templates/form_genero.phtml'; ?>
    </div>
</div>