<div class="container mt-4">
        <tbody>
            <?php foreach ($canciones as $cancion) { ?>
                <tr>
                    <td>
                        <?php
                        if ($id_editar == $cancion->id_cancion) { ?>
                            <form action="updateLetra/<?= $cancion->id_cancion ?>" method="POST">
                                <div class="row">
                                    <div class="col-9">
                                        <div class="form-group">
                                            <h1>Editar letra</h1>
                                        </div>
                                        <div class="form-group">
                                            <textarea name="letra" class="mt-4" rows="50" cols="70"><?= $cancion->letra ?></textarea>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Guardar cambio</button>
                                <a href="volverAbmCancion" type="button" class="btn btn-secondary ml-auto">Volver</a>
                            </form>
                        <?php
                        } else {
                        ?>
                    <td>
                        
                    </td>
                <?php
                        }
                ?>
                </td>
                </tr>
            <?php
            } 
            ?>
        </tbody>
        </table>
    </div>
<?php

//} else {
    //echo "No se pudo acceder a la propiedad del arreglo";
//}
