<div class="container mt-4">
    <table class="table table-striped">
        <tbody>
            <?php foreach ($canciones as $cancion) { ?>
                <tr>
                    <td>
                        <?php if ($id_editar == $cancion->id_cancion) { ?>
                            <form action="updateLetra/<?= $cancion->id_cancion ?>" method="POST">
                                <div class="row">
                                    <div class="col-9">
                                        <div class="form-group">
                                            <h1>Editar letra</h1>
                                        </div>
                                        <div class="form-group">
                                            <textarea name="letra" class="form-control" rows="10" cols="70"><?php echo $cancion->letra ?></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Guardar cambio</button>
                                    <a href="volverAbmCancion" class="btn btn-secondary ml-2">Volver</a>
                                </div>
                            </form>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
