<form class="form" action="agregarGenero" method="POST">
    <div class="form-row">
        <div class="col-9">
            <div class="form-group">
                <label for="descripcion">Descripción</label>
                <input required name="descripcion" type="text" class="form-control">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
