<form action="agregarCancion" method="POST">
    <div class="container">
        <h3 class="mt-4">Agregar nueva canción</h3>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="form-group">
                    <label for="titulo">Título</label>
                    <input required name="titulo" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label for="artista">Artista</label>
                    <input required name="artista" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label for="duracion">Duración</label>
                    <input required name="duracion" type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label for="letra">Letra</label>
                    <textarea required name="letra" class="form-control" rows="10" cols="70"></textarea>
                </div>
                <div class="form-group">
                    <label for="id_genero">Género</label>
                    <select required name="id_genero" id="id_genero" class="form-control">
                        <?php
                        foreach ($generos as $genero) { ?>
                            <option value="<?= $genero->id_genero ?>"><?= $genero->descripcion ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="container">
            <button type="submit" class="btn btn-primary mt-3">Guardar</button>
        </div>
    </div>
</form>