<?php foreach ($genero as $genero) { ?>
    <h1> <?= $genero->descripcion ?> </h1>
<?php } ?>
<ul class="list-group">
    <?php foreach ($canciones as $cancion) { ?>
        <li class="list-group-item">
            <div>
                <a href="contenido/<?php echo $cancion->id_cancion ?>" class="text-decoration-none text-dark">
                    <b><?php echo $cancion->titulo ?> - <?php echo $cancion->artista ?></b>
                </a>
            </div>
        </li>
    <?php } ?>
</ul>
<div>
    <a href="generos" class="btn btn-secondary mt-3">Volver</a>
</div>