<ul class="list-group">
    <?php foreach ($generos as $genero) { ?>
        <li class="list-group-item">
            <a href="filtroCanciones/<?php echo $genero->id_genero ?>" class="text-decoration-none text-dark"><?php echo $genero->descripcion ?></a>
        </li>
    <?php } ?>
    <li class="list-group-item">
        <a href="canciones" class="text-decoration-none text-dark">Todos</a>
    </li>
</ul>
