<?php
require_once 'templates/show_error.phtml';

if (isset($cancion[0]) && isset($cancion[0]->titulo)) {
    $titulo = $cancion[0]->titulo;
    $artista = $cancion[0]->artista;
    $duracion = $cancion[0]->duracion;
    $letra = $cancion[0]->letra;
    $genero = $cancion[0]->descripcion;
?>
    <div class="container mt-4">
        <h1 class="display-4"><?= $genero; ?></h1>
        <h2><?= $titulo; ?> - <?= $artista; ?></h2>
        <h6><?= "Duración: " . $duracion . " minutos"; ?></h6>
        <pre class="mt-4"><?= $letra; ?></pre>
    </div>
    <div class="container mt-4">
            <?php foreach ($cancion as $cancion) { ?>
                        <?php if ($id_editar == $cancion->id_cancion) { ?>
                            <a href="modificarLetra/<?= $cancion->id_cancion ?>" type="button" class='btn btn-success ml-auto'>Editar</a>
                            <a href="volverAbmCancion" type="button" class="btn btn-secondary ml-auto">Volver</a> 
                        <?php } ?>
              <?php } ?>
    </div>
<?php
} else {
    showError("No se pudo acceder a la propiedad del arreglo");
}
